### ISSUE TITLE
Update Data fails during daily automatic build

### ISSUE THREAD

**Issue by saman-moshafi-va** [department-of-veterans-affairs/vets.gov-status#3332]
When starting the build manually or running the code locally, everything works fine, but the builds on Apriul 16 and 17 2020 failed with this stack trace:

```
01:43:51  Traceback (most recent call last):
01:43:51    File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
01:43:51      "__main__", mod_spec)
01:43:51    File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
01:43:51      exec(code, run_globals)
01:43:51    File "/application/fetch_data.py", line 105, in <module>
01:43:51      main()
01:43:51    File "/application/fetch_data.py", line 96, in main
01:43:51      add_csat_data_to_counts(counts, services)
01:43:51    File "/application/fetch_data.py", line 62, in add_csat_data_to_counts
01:43:51      csat_scores_by_service = fetch_foresee_data_for_services(services)
01:43:51    File "/application/foresee/foresee.py", line 145, in fetch_foresee_data_for_services
01:43:51      recent_df, last_year_df = get_foresee_items_for_services()
01:43:51    File "/application/foresee/foresee.py", line 136, in get_foresee_items_for_services
01:43:51      recent_df = pd.DataFrame(make_table_from_foresee_response(recent_items))
01:43:51    File "/application/foresee/foresee_helpers.py", line 7, in make_table_from_foresee_response
01:43:51      'Satisfaction': list(filter(lambda ls: ls['name'] == 'Satisfaction', item['latentScores']))[0]['score'],
01:43:51  IndexError: list index out of range
```

**Comment by saman-moshafi-va** [comment]
I added more logging if the issue occurs again as was unable to reproduce the issue locally

**Comment by saman-moshafi-va** [comment]
I just checked and the last night build was successful
